{{- if not .Values.passwords.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slapd-cluster.fullname" . }}-passwords
  labels:
    {{- include "slapd-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password-hash: {{ .Values.passwords.adminPasswordHash | b64enc | quote }}
  root-password-hash: {{ .Values.passwords.rootPasswordHash | b64enc | quote }}
{{- end }}
