//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapS3Source) DeepCopyInto(out *BootstrapS3Source) {
	*out = *in
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapS3Source.
func (in *BootstrapS3Source) DeepCopy() *BootstrapS3Source {
	if in == nil {
		return nil
	}
	out := new(BootstrapS3Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSource) DeepCopyInto(out *BootstrapSource) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(BootstrapS3Source)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSource.
func (in *BootstrapSource) DeepCopy() *BootstrapSource {
	if in == nil {
		return nil
	}
	out := new(BootstrapSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnConfigCredentials) DeepCopyInto(out *CnConfigCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnConfigCredentials.
func (in *CnConfigCredentials) DeepCopy() *CnConfigCredentials {
	if in == nil {
		return nil
	}
	out := new(CnConfigCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseCredentials) DeepCopyInto(out *DatabaseCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseCredentials.
func (in *DatabaseCredentials) DeepCopy() *DatabaseCredentials {
	if in == nil {
		return nil
	}
	out := new(DatabaseCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseReplicationConfig) DeepCopyInto(out *DatabaseReplicationConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RIDBase != nil {
		in, out := &in.RIDBase, &out.RIDBase
		*out = new(int32)
		**out = **in
	}
	if in.DeltaSync != nil {
		in, out := &in.DeltaSync, &out.DeltaSync
		*out = new(bool)
		**out = **in
	}
	if in.SyncprovSessionlog != nil {
		in, out := &in.SyncprovSessionlog, &out.SyncprovSessionlog
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseReplicationConfig.
func (in *DatabaseReplicationConfig) DeepCopy() *DatabaseReplicationConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseReplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSeedConfig) DeepCopyInto(out *DatabaseSeedConfig) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSeedConfig.
func (in *DatabaseSeedConfig) DeepCopy() *DatabaseSeedConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseSeedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPeer) DeepCopyInto(out *ExternalPeer) {
	*out = *in
	if in.PodAddresses != nil {
		in, out := &in.PodAddresses, &out.PodAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Discovery != nil {
		in, out := &in.Discovery, &out.Discovery
		*out = new(ExternalPeerDiscovery)
		**out = **in
	}
	if in.ReplicasPerPeer != nil {
		in, out := &in.ReplicasPerPeer, &out.ReplicasPerPeer
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPeer.
func (in *ExternalPeer) DeepCopy() *ExternalPeer {
	if in == nil {
		return nil
	}
	out := new(ExternalPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPeerDiscovery) DeepCopyInto(out *ExternalPeerDiscovery) {
	*out = *in
	out.KubeconfigSecret = in.KubeconfigSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPeerDiscovery.
func (in *ExternalPeerDiscovery) DeepCopy() *ExternalPeerDiscovery {
	if in == nil {
		return nil
	}
	out := new(ExternalPeerDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPeerStatus) DeepCopyInto(out *ExternalPeerStatus) {
	*out = *in
	if in.DiscoveredAddresses != nil {
		in, out := &in.DiscoveredAddresses, &out.DiscoveredAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPeerStatus.
func (in *ExternalPeerStatus) DeepCopy() *ExternalPeerStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigSecretRef) DeepCopyInto(out *KubeconfigSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigSecretRef.
func (in *KubeconfigSecretRef) DeepCopy() *KubeconfigSecretRef {
	if in == nil {
		return nil
	}
	out := new(KubeconfigSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationNetworkConfig) DeepCopyInto(out *ReplicationNetworkConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationNetworkConfig.
func (in *ReplicationNetworkConfig) DeepCopy() *ReplicationNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(ReplicationNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSource) DeepCopyInto(out *RestoreSource) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(BootstrapS3Source)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSource.
func (in *RestoreSource) DeepCopy() *RestoreSource {
	if in == nil {
		return nil
	}
	out := new(RestoreSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3StorageSpec) DeepCopyInto(out *S3StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3StorageSpec.
func (in *S3StorageSpec) DeepCopy() *S3StorageSpec {
	if in == nil {
		return nil
	}
	out := new(S3StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledBackupRetention) DeepCopyInto(out *ScheduledBackupRetention) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledBackupRetention.
func (in *ScheduledBackupRetention) DeepCopy() *ScheduledBackupRetention {
	if in == nil {
		return nil
	}
	out := new(ScheduledBackupRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdBackup) DeepCopyInto(out *SlapdBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdBackup.
func (in *SlapdBackup) DeepCopy() *SlapdBackup {
	if in == nil {
		return nil
	}
	out := new(SlapdBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdBackupList) DeepCopyInto(out *SlapdBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlapdBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdBackupList.
func (in *SlapdBackupList) DeepCopy() *SlapdBackupList {
	if in == nil {
		return nil
	}
	out := new(SlapdBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdBackupSpec) DeepCopyInto(out *SlapdBackupSpec) {
	*out = *in
	out.Storage = in.Storage
	if in.PodAffinity != nil {
		in, out := &in.PodAffinity, &out.PodAffinity
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdBackupSpec.
func (in *SlapdBackupSpec) DeepCopy() *SlapdBackupSpec {
	if in == nil {
		return nil
	}
	out := new(SlapdBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdBackupStatus) DeepCopyInto(out *SlapdBackupStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.SourceContextCSN != nil {
		in, out := &in.SourceContextCSN, &out.SourceContextCSN
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdBackupStatus.
func (in *SlapdBackupStatus) DeepCopy() *SlapdBackupStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdCluster) DeepCopyInto(out *SlapdCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdCluster.
func (in *SlapdCluster) DeepCopy() *SlapdCluster {
	if in == nil {
		return nil
	}
	out := new(SlapdCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdClusterList) DeepCopyInto(out *SlapdClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlapdCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdClusterList.
func (in *SlapdClusterList) DeepCopy() *SlapdClusterList {
	if in == nil {
		return nil
	}
	out := new(SlapdClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdClusterRestoreStatus) DeepCopyInto(out *SlapdClusterRestoreStatus) {
	*out = *in
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdClusterRestoreStatus.
func (in *SlapdClusterRestoreStatus) DeepCopy() *SlapdClusterRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdClusterRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdClusterSpec) DeepCopyInto(out *SlapdClusterSpec) {
	*out = *in
	out.Images = in.Images
	in.LDAP.DeepCopyInto(&out.LDAP)
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(int32)
		**out = **in
	}
	in.Tuning.DeepCopyInto(&out.Tuning)
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(SlapdMdbBackendConfig)
		(*in).DeepCopyInto(*out)
	}
	out.Persistence = in.Persistence
	in.Service.DeepCopyInto(&out.Service)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Replication.DeepCopyInto(&out.Replication)
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdClusterSpec.
func (in *SlapdClusterSpec) DeepCopy() *SlapdClusterSpec {
	if in == nil {
		return nil
	}
	out := new(SlapdClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdClusterStatus) DeepCopyInto(out *SlapdClusterStatus) {
	*out = *in
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(SlapdClusterRestoreStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ReplicationNetworkIPs != nil {
		in, out := &in.ReplicationNetworkIPs, &out.ReplicationNetworkIPs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExternalPeerStatuses != nil {
		in, out := &in.ExternalPeerStatuses, &out.ExternalPeerStatuses
		*out = make([]ExternalPeerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdClusterStatus.
func (in *SlapdClusterStatus) DeepCopy() *SlapdClusterStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdDatabase) DeepCopyInto(out *SlapdDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdDatabase.
func (in *SlapdDatabase) DeepCopy() *SlapdDatabase {
	if in == nil {
		return nil
	}
	out := new(SlapdDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdDatabaseList) DeepCopyInto(out *SlapdDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlapdDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdDatabaseList.
func (in *SlapdDatabaseList) DeepCopy() *SlapdDatabaseList {
	if in == nil {
		return nil
	}
	out := new(SlapdDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdDatabaseSpec) DeepCopyInto(out *SlapdDatabaseSpec) {
	*out = *in
	out.Credentials = in.Credentials
	if in.SizeLimit != nil {
		in, out := &in.SizeLimit, &out.SizeLimit
		*out = new(string)
		**out = **in
	}
	if in.TimeLimit != nil {
		in, out := &in.TimeLimit, &out.TimeLimit
		*out = new(string)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NoSync != nil {
		in, out := &in.NoSync, &out.NoSync
		*out = new(bool)
		**out = **in
	}
	if in.Checkpoint != nil {
		in, out := &in.Checkpoint, &out.Checkpoint
		*out = new(string)
		**out = **in
	}
	if in.RtxnSize != nil {
		in, out := &in.RtxnSize, &out.RtxnSize
		*out = new(int32)
		**out = **in
	}
	if in.EnvFlags != nil {
		in, out := &in.EnvFlags, &out.EnvFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ACLs != nil {
		in, out := &in.ACLs, &out.ACLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Indices != nil {
		in, out := &in.Indices, &out.Indices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Replication.DeepCopyInto(&out.Replication)
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(DatabaseSeedConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BootstrapFrom != nil {
		in, out := &in.BootstrapFrom, &out.BootstrapFrom
		*out = new(BootstrapSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdDatabaseSpec.
func (in *SlapdDatabaseSpec) DeepCopy() *SlapdDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(SlapdDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdDatabaseStatus) DeepCopyInto(out *SlapdDatabaseStatus) {
	*out = *in
	if in.AppliedToPods != nil {
		in, out := &in.AppliedToPods, &out.AppliedToPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedPods != nil {
		in, out := &in.FailedPods, &out.FailedPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdDatabaseStatus.
func (in *SlapdDatabaseStatus) DeepCopy() *SlapdDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdImageConfig) DeepCopyInto(out *SlapdImageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdImageConfig.
func (in *SlapdImageConfig) DeepCopy() *SlapdImageConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdImages) DeepCopyInto(out *SlapdImages) {
	*out = *in
	out.Slapd = in.Slapd
	out.Init = in.Init
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdImages.
func (in *SlapdImages) DeepCopy() *SlapdImages {
	if in == nil {
		return nil
	}
	out := new(SlapdImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdLDAPConfig) DeepCopyInto(out *SlapdLDAPConfig) {
	*out = *in
	out.CnConfigCredentials = in.CnConfigCredentials
	in.TLS.DeepCopyInto(&out.TLS)
	if in.PasswordHash != nil {
		in, out := &in.PasswordHash, &out.PasswordHash
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdLDAPConfig.
func (in *SlapdLDAPConfig) DeepCopy() *SlapdLDAPConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdLDAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdMdbBackendConfig) DeepCopyInto(out *SlapdMdbBackendConfig) {
	*out = *in
	if in.IDLExponent != nil {
		in, out := &in.IDLExponent, &out.IDLExponent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdMdbBackendConfig.
func (in *SlapdMdbBackendConfig) DeepCopy() *SlapdMdbBackendConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdMdbBackendConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdPVCConfig) DeepCopyInto(out *SlapdPVCConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdPVCConfig.
func (in *SlapdPVCConfig) DeepCopy() *SlapdPVCConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdPVCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdPersistenceConfig) DeepCopyInto(out *SlapdPersistenceConfig) {
	*out = *in
	out.Config = in.Config
	out.Data = in.Data
	out.Accesslog = in.Accesslog
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdPersistenceConfig.
func (in *SlapdPersistenceConfig) DeepCopy() *SlapdPersistenceConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdPersistenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdReplicationConfig) DeepCopyInto(out *SlapdReplicationConfig) {
	*out = *in
	if in.AccesslogEnabled != nil {
		in, out := &in.AccesslogEnabled, &out.AccesslogEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ExternalPeers != nil {
		in, out := &in.ExternalPeers, &out.ExternalPeers
		*out = make([]ExternalPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(ReplicationNetworkConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdReplicationConfig.
func (in *SlapdReplicationConfig) DeepCopy() *SlapdReplicationConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdReplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdRestore) DeepCopyInto(out *SlapdRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdRestore.
func (in *SlapdRestore) DeepCopy() *SlapdRestore {
	if in == nil {
		return nil
	}
	out := new(SlapdRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdRestoreList) DeepCopyInto(out *SlapdRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlapdRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdRestoreList.
func (in *SlapdRestoreList) DeepCopy() *SlapdRestoreList {
	if in == nil {
		return nil
	}
	out := new(SlapdRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdRestoreSpec) DeepCopyInto(out *SlapdRestoreSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdRestoreSpec.
func (in *SlapdRestoreSpec) DeepCopy() *SlapdRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(SlapdRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdRestoreStatus) DeepCopyInto(out *SlapdRestoreStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdRestoreStatus.
func (in *SlapdRestoreStatus) DeepCopy() *SlapdRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdScheduledBackup) DeepCopyInto(out *SlapdScheduledBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdScheduledBackup.
func (in *SlapdScheduledBackup) DeepCopy() *SlapdScheduledBackup {
	if in == nil {
		return nil
	}
	out := new(SlapdScheduledBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdScheduledBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdScheduledBackupList) DeepCopyInto(out *SlapdScheduledBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlapdScheduledBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdScheduledBackupList.
func (in *SlapdScheduledBackupList) DeepCopy() *SlapdScheduledBackupList {
	if in == nil {
		return nil
	}
	out := new(SlapdScheduledBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdScheduledBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdScheduledBackupSpec) DeepCopyInto(out *SlapdScheduledBackupSpec) {
	*out = *in
	out.Storage = in.Storage
	out.Retention = in.Retention
	if in.PodAffinity != nil {
		in, out := &in.PodAffinity, &out.PodAffinity
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdScheduledBackupSpec.
func (in *SlapdScheduledBackupSpec) DeepCopy() *SlapdScheduledBackupSpec {
	if in == nil {
		return nil
	}
	out := new(SlapdScheduledBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdScheduledBackupStatus) DeepCopyInto(out *SlapdScheduledBackupStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleTime != nil {
		in, out := &in.NextScheduleTime, &out.NextScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdScheduledBackupStatus.
func (in *SlapdScheduledBackupStatus) DeepCopy() *SlapdScheduledBackupStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdScheduledBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdSchema) DeepCopyInto(out *SlapdSchema) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdSchema.
func (in *SlapdSchema) DeepCopy() *SlapdSchema {
	if in == nil {
		return nil
	}
	out := new(SlapdSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdSchema) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdSchemaList) DeepCopyInto(out *SlapdSchemaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlapdSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdSchemaList.
func (in *SlapdSchemaList) DeepCopy() *SlapdSchemaList {
	if in == nil {
		return nil
	}
	out := new(SlapdSchemaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdSchemaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdSchemaSpec) DeepCopyInto(out *SlapdSchemaSpec) {
	*out = *in
	if in.AttributeTypes != nil {
		in, out := &in.AttributeTypes, &out.AttributeTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObjectClasses != nil {
		in, out := &in.ObjectClasses, &out.ObjectClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdSchemaSpec.
func (in *SlapdSchemaSpec) DeepCopy() *SlapdSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(SlapdSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdSchemaStatus) DeepCopyInto(out *SlapdSchemaStatus) {
	*out = *in
	if in.AppliedToPods != nil {
		in, out := &in.AppliedToPods, &out.AppliedToPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedPods != nil {
		in, out := &in.FailedPods, &out.FailedPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdSchemaStatus.
func (in *SlapdSchemaStatus) DeepCopy() *SlapdSchemaStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdSchemaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdServiceConfig) DeepCopyInto(out *SlapdServiceConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LoadBalancerSourceRanges != nil {
		in, out := &in.LoadBalancerSourceRanges, &out.LoadBalancerSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdServiceConfig.
func (in *SlapdServiceConfig) DeepCopy() *SlapdServiceConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdTLSConfig) DeepCopyInto(out *SlapdTLSConfig) {
	*out = *in
	if in.ProtocolMin != nil {
		in, out := &in.ProtocolMin, &out.ProtocolMin
		*out = new(string)
		**out = **in
	}
	if in.CipherSuite != nil {
		in, out := &in.CipherSuite, &out.CipherSuite
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdTLSConfig.
func (in *SlapdTLSConfig) DeepCopy() *SlapdTLSConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdTuningConfig) DeepCopyInto(out *SlapdTuningConfig) {
	*out = *in
	if in.ToolThreads != nil {
		in, out := &in.ToolThreads, &out.ToolThreads
		*out = new(int32)
		**out = **in
	}
	if in.NoSync != nil {
		in, out := &in.NoSync, &out.NoSync
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdTuningConfig.
func (in *SlapdTuningConfig) DeepCopy() *SlapdTuningConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdTuningConfig)
	in.DeepCopyInto(out)
	return out
}
