//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnConfigCredentials) DeepCopyInto(out *CnConfigCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnConfigCredentials.
func (in *CnConfigCredentials) DeepCopy() *CnConfigCredentials {
	if in == nil {
		return nil
	}
	out := new(CnConfigCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseCredentials) DeepCopyInto(out *DatabaseCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseCredentials.
func (in *DatabaseCredentials) DeepCopy() *DatabaseCredentials {
	if in == nil {
		return nil
	}
	out := new(DatabaseCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseReplicationConfig) DeepCopyInto(out *DatabaseReplicationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseReplicationConfig.
func (in *DatabaseReplicationConfig) DeepCopy() *DatabaseReplicationConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseReplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSeedConfig) DeepCopyInto(out *DatabaseSeedConfig) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSeedConfig.
func (in *DatabaseSeedConfig) DeepCopy() *DatabaseSeedConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseSeedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPeer) DeepCopyInto(out *ExternalPeer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPeer.
func (in *ExternalPeer) DeepCopy() *ExternalPeer {
	if in == nil {
		return nil
	}
	out := new(ExternalPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPeerStatus) DeepCopyInto(out *ExternalPeerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPeerStatus.
func (in *ExternalPeerStatus) DeepCopy() *ExternalPeerStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdCluster) DeepCopyInto(out *SlapdCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdCluster.
func (in *SlapdCluster) DeepCopy() *SlapdCluster {
	if in == nil {
		return nil
	}
	out := new(SlapdCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdClusterList) DeepCopyInto(out *SlapdClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlapdCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdClusterList.
func (in *SlapdClusterList) DeepCopy() *SlapdClusterList {
	if in == nil {
		return nil
	}
	out := new(SlapdClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdClusterSpec) DeepCopyInto(out *SlapdClusterSpec) {
	*out = *in
	out.Images = in.Images
	out.LDAP = in.LDAP
	out.Persistence = in.Persistence
	out.Service = in.Service
	in.Resources.DeepCopyInto(&out.Resources)
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Replication.DeepCopyInto(&out.Replication)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdClusterSpec.
func (in *SlapdClusterSpec) DeepCopy() *SlapdClusterSpec {
	if in == nil {
		return nil
	}
	out := new(SlapdClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdClusterStatus) DeepCopyInto(out *SlapdClusterStatus) {
	*out = *in
	if in.ExternalPeerStatuses != nil {
		in, out := &in.ExternalPeerStatuses, &out.ExternalPeerStatuses
		*out = make([]ExternalPeerStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdClusterStatus.
func (in *SlapdClusterStatus) DeepCopy() *SlapdClusterStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdDatabase) DeepCopyInto(out *SlapdDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdDatabase.
func (in *SlapdDatabase) DeepCopy() *SlapdDatabase {
	if in == nil {
		return nil
	}
	out := new(SlapdDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdDatabaseList) DeepCopyInto(out *SlapdDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlapdDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdDatabaseList.
func (in *SlapdDatabaseList) DeepCopy() *SlapdDatabaseList {
	if in == nil {
		return nil
	}
	out := new(SlapdDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdDatabaseSpec) DeepCopyInto(out *SlapdDatabaseSpec) {
	*out = *in
	out.Credentials = in.Credentials
	if in.ACLs != nil {
		in, out := &in.ACLs, &out.ACLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Indices != nil {
		in, out := &in.Indices, &out.Indices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(DatabaseReplicationConfig)
		**out = **in
	}
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(DatabaseSeedConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdDatabaseSpec.
func (in *SlapdDatabaseSpec) DeepCopy() *SlapdDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(SlapdDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdDatabaseStatus) DeepCopyInto(out *SlapdDatabaseStatus) {
	*out = *in
	if in.AppliedToPods != nil {
		in, out := &in.AppliedToPods, &out.AppliedToPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedPods != nil {
		in, out := &in.FailedPods, &out.FailedPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdDatabaseStatus.
func (in *SlapdDatabaseStatus) DeepCopy() *SlapdDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdImageConfig) DeepCopyInto(out *SlapdImageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdImageConfig.
func (in *SlapdImageConfig) DeepCopy() *SlapdImageConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdImages) DeepCopyInto(out *SlapdImages) {
	*out = *in
	out.Slapd = in.Slapd
	out.Init = in.Init
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdImages.
func (in *SlapdImages) DeepCopy() *SlapdImages {
	if in == nil {
		return nil
	}
	out := new(SlapdImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdLDAPConfig) DeepCopyInto(out *SlapdLDAPConfig) {
	*out = *in
	out.CnConfigCredentials = in.CnConfigCredentials
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdLDAPConfig.
func (in *SlapdLDAPConfig) DeepCopy() *SlapdLDAPConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdLDAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdPVCConfig) DeepCopyInto(out *SlapdPVCConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdPVCConfig.
func (in *SlapdPVCConfig) DeepCopy() *SlapdPVCConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdPVCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdPersistenceConfig) DeepCopyInto(out *SlapdPersistenceConfig) {
	*out = *in
	out.Config = in.Config
	out.Data = in.Data
	out.Accesslog = in.Accesslog
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdPersistenceConfig.
func (in *SlapdPersistenceConfig) DeepCopy() *SlapdPersistenceConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdPersistenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdReplicationConfig) DeepCopyInto(out *SlapdReplicationConfig) {
	*out = *in
	if in.ExternalPeers != nil {
		in, out := &in.ExternalPeers, &out.ExternalPeers
		*out = make([]ExternalPeer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdReplicationConfig.
func (in *SlapdReplicationConfig) DeepCopy() *SlapdReplicationConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdReplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdSchema) DeepCopyInto(out *SlapdSchema) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdSchema.
func (in *SlapdSchema) DeepCopy() *SlapdSchema {
	if in == nil {
		return nil
	}
	out := new(SlapdSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdSchema) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdSchemaList) DeepCopyInto(out *SlapdSchemaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlapdSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdSchemaList.
func (in *SlapdSchemaList) DeepCopy() *SlapdSchemaList {
	if in == nil {
		return nil
	}
	out := new(SlapdSchemaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdSchemaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdSchemaSpec) DeepCopyInto(out *SlapdSchemaSpec) {
	*out = *in
	if in.AttributeTypes != nil {
		in, out := &in.AttributeTypes, &out.AttributeTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObjectClasses != nil {
		in, out := &in.ObjectClasses, &out.ObjectClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdSchemaSpec.
func (in *SlapdSchemaSpec) DeepCopy() *SlapdSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(SlapdSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdSchemaStatus) DeepCopyInto(out *SlapdSchemaStatus) {
	*out = *in
	if in.AppliedToPods != nil {
		in, out := &in.AppliedToPods, &out.AppliedToPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedPods != nil {
		in, out := &in.FailedPods, &out.FailedPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdSchemaStatus.
func (in *SlapdSchemaStatus) DeepCopy() *SlapdSchemaStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdSchemaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdServiceConfig) DeepCopyInto(out *SlapdServiceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdServiceConfig.
func (in *SlapdServiceConfig) DeepCopy() *SlapdServiceConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdTLSConfig) DeepCopyInto(out *SlapdTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdTLSConfig.
func (in *SlapdTLSConfig) DeepCopy() *SlapdTLSConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdTLSConfig)
	in.DeepCopyInto(out)
	return out
}
