//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPeer) DeepCopyInto(out *ExternalPeer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPeer.
func (in *ExternalPeer) DeepCopy() *ExternalPeer {
	if in == nil {
		return nil
	}
	out := new(ExternalPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerRef) DeepCopyInto(out *PeerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerRef.
func (in *PeerRef) DeepCopy() *PeerRef {
	if in == nil {
		return nil
	}
	out := new(PeerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdCluster) DeepCopyInto(out *SlapdCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdCluster.
func (in *SlapdCluster) DeepCopy() *SlapdCluster {
	if in == nil {
		return nil
	}
	out := new(SlapdCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdClusterList) DeepCopyInto(out *SlapdClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlapdCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdClusterList.
func (in *SlapdClusterList) DeepCopy() *SlapdClusterList {
	if in == nil {
		return nil
	}
	out := new(SlapdClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlapdClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdClusterSpec) DeepCopyInto(out *SlapdClusterSpec) {
	*out = *in
	out.Images = in.Images
	out.LDAP = in.LDAP
	out.Persistence = in.Persistence
	out.Service = in.Service
	in.Resources.DeepCopyInto(&out.Resources)
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Replication.DeepCopyInto(&out.Replication)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdClusterSpec.
func (in *SlapdClusterSpec) DeepCopy() *SlapdClusterSpec {
	if in == nil {
		return nil
	}
	out := new(SlapdClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdClusterStatus) DeepCopyInto(out *SlapdClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdClusterStatus.
func (in *SlapdClusterStatus) DeepCopy() *SlapdClusterStatus {
	if in == nil {
		return nil
	}
	out := new(SlapdClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdImageConfig) DeepCopyInto(out *SlapdImageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdImageConfig.
func (in *SlapdImageConfig) DeepCopy() *SlapdImageConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdImages) DeepCopyInto(out *SlapdImages) {
	*out = *in
	out.Slapd = in.Slapd
	out.Init = in.Init
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdImages.
func (in *SlapdImages) DeepCopy() *SlapdImages {
	if in == nil {
		return nil
	}
	out := new(SlapdImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdLDAPConfig) DeepCopyInto(out *SlapdLDAPConfig) {
	*out = *in
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdLDAPConfig.
func (in *SlapdLDAPConfig) DeepCopy() *SlapdLDAPConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdLDAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdPVCConfig) DeepCopyInto(out *SlapdPVCConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdPVCConfig.
func (in *SlapdPVCConfig) DeepCopy() *SlapdPVCConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdPVCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdPersistenceConfig) DeepCopyInto(out *SlapdPersistenceConfig) {
	*out = *in
	out.Config = in.Config
	out.Data = in.Data
	out.Accesslog = in.Accesslog
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdPersistenceConfig.
func (in *SlapdPersistenceConfig) DeepCopy() *SlapdPersistenceConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdPersistenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdReplicationConfig) DeepCopyInto(out *SlapdReplicationConfig) {
	*out = *in
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]PeerRef, len(*in))
		copy(*out, *in)
	}
	if in.ExternalPeers != nil {
		in, out := &in.ExternalPeers, &out.ExternalPeers
		*out = make([]ExternalPeer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdReplicationConfig.
func (in *SlapdReplicationConfig) DeepCopy() *SlapdReplicationConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdReplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdServiceConfig) DeepCopyInto(out *SlapdServiceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdServiceConfig.
func (in *SlapdServiceConfig) DeepCopy() *SlapdServiceConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlapdTLSConfig) DeepCopyInto(out *SlapdTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlapdTLSConfig.
func (in *SlapdTLSConfig) DeepCopy() *SlapdTLSConfig {
	if in == nil {
		return nil
	}
	out := new(SlapdTLSConfig)
	in.DeepCopyInto(out)
	return out
}
