apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-manager
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - secrets
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ldap.chuck-chuck-chuck.net
    resources:
      - slapdclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ldap.chuck-chuck-chuck.net
    resources:
      - slapdclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - ldap.chuck-chuck-chuck.net
    resources:
      - slapdclusters/status
    verbs:
      - get
      - patch
      - update
