---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldap.chuck-chuck-chuck.net
  resources:
  - slapdclusters
  - slapddatabases
  - slapdschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldap.chuck-chuck-chuck.net
  resources:
  - slapdclusters/finalizers
  - slapddatabases/finalizers
  - slapdschemas/finalizers
  verbs:
  - update
- apiGroups:
  - ldap.chuck-chuck-chuck.net
  resources:
  - slapdclusters/status
  - slapddatabases/status
  - slapdschemas/status
  verbs:
  - get
  - patch
  - update
