{{- if .Values.bootstrap.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "slapd-test.fullname" . }}
  labels:
    {{- include "slapd-test.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: tester
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LDAP_ADMIN_PW
              valueFrom:
                secretKeyRef:
                  name: {{ coalesce .Values.slapd.secretName .Values.slapd.passwordsSecretName (printf "%s-passwords" (include "slapd-test.fullname" .)) }}
                  key: admin-password
            - name: LDAP_ROOT_PW
              valueFrom:
                secretKeyRef:
                  name: {{ coalesce .Values.slapd.secretName .Values.slapd.configPasswordSecretName (printf "%s-passwords" (include "slapd-test.fullname" .)) }}
                  key: root-password
            - name: LDAPTLS_CACERT
              value: /etc/ldap/tls/ca.crt
            - name: SLAPD_HOST
              value: {{ .Values.slapd.fullname | quote }}
            - name: LDAP_DOMAIN
              value: {{ .Values.slapd.domain | quote }}
            - name: READPW_OU
              value: {{ .Values.bootstrap.readpwOU | quote }}
          command: ["bash", "/config/bootstrap.sh"]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: ca-cert
              mountPath: /etc/ldap/tls
      volumes:
        - name: config
          configMap:
            name: {{ include "slapd-test.fullname" . }}-config
        - name: ca-cert
          configMap:
            name: kube-root-ca.crt
{{- end }}
