{{- if not .Values.slapd.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slapd-test.fullname" . }}-passwords
  labels:
    {{- include "slapd-test.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.slapd.adminPassword | b64enc | quote }}
  root-password: {{ .Values.slapd.rootPassword | b64enc | quote }}
{{- end }}
