apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slapd-test.fullname" . }}-passwords
  labels:
    {{- include "slapd-test.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (or .Values.slapd.passwordsSecretName .Values.slapd.secretName) }}
  admin-password: {{ required "slapd.adminPassword is required when slapd.secretName and slapd.passwordsSecretName are not set" .Values.slapd.adminPassword | b64enc | quote }}
  {{- end }}
  {{- if not (or .Values.slapd.configPasswordSecretName .Values.slapd.secretName) }}
  root-password: {{ required "slapd.rootPassword is required when slapd.secretName and slapd.configPasswordSecretName are not set" .Values.slapd.rootPassword | b64enc | quote }}
  {{- end }}
  {{- range $user, $pw := .Values.bootstrap.readpwPasswords }}
  readpw-{{ $user }}: {{ $pw | b64enc | quote }}
  {{- end }}
