{{- if not .Values.slapd.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slapd-test.fullname" . }}-passwords
  labels:
    {{- include "slapd-test.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ required "slapd.adminPassword is required when slapd.secretName is not set" .Values.slapd.adminPassword | b64enc | quote }}
  root-password: {{ required "slapd.rootPassword is required when slapd.secretName is not set" .Values.slapd.rootPassword | b64enc | quote }}
{{- range $user, $pw := .Values.bootstrap.readpwPasswords }}
  readpw-{{ $user }}: {{ $pw | b64enc | quote }}
{{- end }}
{{- end }}
