{{- if not .Values.passwords.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slapd.fullname" . }}-passwords
  labels:
    {{- include "slapd.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ required "passwords.adminPassword is required when passwords.existingSecret is not set" .Values.passwords.adminPassword | b64enc | quote }}
  root-password: {{ required "passwords.rootPassword is required when passwords.existingSecret is not set" .Values.passwords.rootPassword | b64enc | quote }}
{{- end }}
